/*
1.
*/
SELECT STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;


/*
2.
*/
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE NOT LENGTH(PROFESSOR_NAME) = 3;

/*
3.
*/
SELECT PROFESSOR_NAME 교수이름,EXTRACT(YEAR FROM SYSDATE)- CONCAT('19' , SUBSTR(EXTRACT(YEAR FROM (TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'YYMMDD'))),3,2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1)= '1'
ORDER BY 나이;



/*
4.
*/
SELECT SUBSTR(PROFESSOR_NAME,2,2) 이름
FROM TB_PROFESSOR;


/*
5.
*/
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM TO_DATE(ENTRANCE_DATE))- CONCAT('19' , SUBSTR(STUDENT_SSN,1,2)) > 19;


/*
6.
*/
SELECT TO_CHAR(TO_DATE('2020/12/25'),'DAY') FROM DUAL;


/*
7. 
*/
/*
TO_DATE('99/10/11', 'YY/MM/DD') --> 2099/10/11
TO_DATE('49/10/11', 'YY/MM/DD') --> 2049/10/11  현재세기 의미한다

TO_DATE('99/10/11', 'RR/MM/DD') --> 1999/10/11
TO_DATE('49/10/11', 'RR/MM/DD') --> 2049/10/11  
-- RR > 50 은 현재세기, RR <= 50 은 지난세기
*/


/*
8.
*/
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%';


/*
9.
*/
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


/*
10.
*/
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;


/*
11.
*/
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;


/*
12.
*/
SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND((SUM(POINT)/COUNT(POINT)), 1) "년도 별 평점"
FROM TB_GRADE
GROUP BY SUBSTR(TERM_NO,1,4), STUDENT_NO
HAVING STUDENT_NO = 'A112113';


/*
13.
*/

SELECT DEPARTMENT_NO "학과코드명", COUNT(DECODE(ABSENCE_YN, 'Y', 1, NULL)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- COUNT(DECODE(ABSENCE_YN, 'Y', 1, NULL)) 의 부연설명
-- 만일 ABSENCE_YN의 값이 'Y'였을 경우 COUNT(1)이 되어 갯수를 세게 되고
--     ABSENCE_YN의 값이 'Y'가 아니였을 경우 COUNT(NULL)이 되어 갯수를 세지 않게되는 원리!!



/*
14.
*/

SELECT STUDENT_NAME "동일이름", COUNT(*)"동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME)>1
ORDER BY STUDENT_NAME;


/*
15.
*/

SELECT SUBSTR(TERM_NO,1,4) "년도", SUBSTR(TERM_NO, 5, 2) "학기", ROUND(AVG(POINT),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP ( SUBSTR(TERM_NO,1,4) , SUBSTR(TERM_NO, 5, 2))
ORDER BY "년도";










