/*
1.
*/
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
GROUP BY STUDENT_NAME, STUDENT_ADDRESS
ORDER BY STUDENT_NAME;


/*
2.
*/
SELECT STUDENT_NAME, STUDENT_SSN
FROM tb_student
WHERE absence_yn = 'Y'
GROUP BY STUDENT_NAME, STUDENT_SSN
ORDER BY STUDENT_SSN DESC;


/*
3.
*/
SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%강원도%' OR STUDENT_ADDRESS LIKE '%경기도%'
  AND STUDENT_NO LIKE '9______'
GROUP BY STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
ORDER BY STUDENT_NAME;


/*
4.
*/
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM tb_professor
JOIN tb_department USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;


/*
5.
*/
SELECT STUDENT_NO, TO_CHAR(POINT,'9.99')학점
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN tb_class USING (CLASS_NO)
WHERE TERM_NO = '200402'
  AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;


/*
6.
*/
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM tb_student
JOIN tb_department USING(DEPARTMENT_NO);


/*
7.
*/
-->> 오라클 구문
SELECT C.CLASS_NAME, D.DEPARTMENT_NAME
FROM TB_CLASS C, TB_DEPARTMENT D
WHERE c.department_no = d.department_no;

-->> ANSI 구문
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);


/*
8.
*/
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
ORDER BY 2,1 ;


/*
9.
*/
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_PROFESSOR P USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (P.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회'
ORDER BY 2,1 ;


/*
10.
*/
SELECT S.STUDENT_NO 학번, STUDENT_NAME 학생이름, ROUND(AVG(POINT),1) 전체평점
FROM TB_STUDENT S, TB_GRADE G, TB_DEPARTMENT D
WHERE S.STUDENT_NO = G.STUDENT_NO
AND D.DEPARTMENT_NO = S.DEPARTMENT_NO
AND DEPARTMENT_NAME = '음악학과'
GROUP BY S.STUDENT_NO, STUDENT_NAME
ORDER BY 1;


/*
11. 
*/
SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_PROFESSOR P
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND COACH_PROFESSOR_NO = PROFESSOR_NO
AND STUDENT_NO = 'A313047';


/*
12
*/
SELECT STUDENT_NAME, TERM_NO "TERM NAME"
FROM TB_STUDENT S, TB_GRADE G, TB_CLASS C
WHERE S.STUDENT_NO = G.STUDENT_NO
AND G.CLASS_NO = C.CLASS_NO
AND CLASS_NAME = '인간관계론'
AND TERM_NO LIKE '2007%';



/*
13.
*/
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN tb_class_professor USING (CLASS_NO)
JOIN tb_department USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL
ORDER BY 2,1 ;    -- NULL 값 제외

/*
14.
*/
SELECT STUDENT_NAME, NVL(PROFESSOR_NAME, '지도교수 미지정')
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;



/*
15.
*/
SELECT S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME, AVG(POINT)
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_GRADE G
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND S.STUDENT_NO = G.STUDENT_NO
AND ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY 1;


/*
16.
*/
SELECT C.CLASS_NO, C.CLASS_NAME, AVG(POINT)
FROM TB_CLASS C, TB_GRADE G, TB_DEPARTMENT D
WHERE C.CLASS_NO = G.CLASS_NO
AND C.DEPARTMENT_NO = D.DEPARTMENT_NO
AND DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '%전공%'
GROUP BY C.CLASS_NO, CLASS_NAME;


/*
17.
*/
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                        FROM TB_STUDENT
                        WHERE STUDENT_NAME = '최경희');


/*
18.
*/
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
                      FROM TB_STUDENT
                      JOIN TB_GRADE USING(STUDENT_NO)
                      JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                      WHERE DEPARTMENT_NAME = '국어국문학과'
                      GROUP BY STUDENT_NO);


/*
19.
*/
SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) "전공평점"
FROM TB_DEPARTMENT
JOIN TB_CLASS USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY
                    FROM TB_DEPARTMENT
                    WHERE DEPARTMENT_NAME = '환경조경학과'
                 )
AND CLASS_TYPE LIKE '%전공%'
GROUP BY DEPARTMENT_NAME
ORDER BY 1;
























