/*
1.
*/
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);


/*
2.
*/
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) CONSTRAINT NO_PK PRIMARY KEY,
    NAME VARCHAR2(10)
);

/*
3.
*/
ALTER TABLE TB_CATEGORY ADD CONSTRAINT NAME_PK PRIMARY KEY(NAME);


/*
4. 
*/
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(10) NOT NULL;


/*
5.
*/
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);


/*
6.
*/
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;


/*
7.
*/
ALTER TABLE TB_CATEGORY 
RENAME CONSTRAINT NAME_PK TO PK_CATEGORY_NAME; 

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT NO_PK TO PK_CLASS_TYPE_NO;

/*
8.
*/
INSERT INTO TB_CATEGORY VALUES('공학', DEFAULT);
INSERT INTO TB_CATEGORY VALUES('자연과학', DEFAULT);
INSERT INTO TB_CATEGORY VALUES('의학', DEFAULT);
INSERT INTO TB_CATEGORY VALUES('예체능', DEFAULT);
INSERT INTO TB_CATEGORY VALUES('인문사회', DEFAULT);

COMMIT;


/*
9.
*/
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY
FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);


/*
10
*/
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT;

SELECT * FROM VW_학생일반정보;


/*
11.
*/
CREATE OR REPLACE VIEW VW_지도면담
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, NVL(PROFESSOR_NAME, '담당교수없음') 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
ORDER BY DEPARTMENT_NAME;

SELECT * FROM "VW_지도면담";


/*
12.
*/
CREATE OR REPLACE VIEW VW_학과별학생수 (DEPARTMENT_NAME, STUDENT_COUNT)
AS SELECT DEPARTMENT_NAME, COUNT(*)
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME;

SELECT * FROM VW_학과별학생수;


/*
13.
*/
UPDATE VW_학생일반정보
   SET 학생이름 = '본인이름'
 WHERE 학번 = 'A213046';

/*
14.
*/
CREATE OR REPLACE VIEW VW_학생일반정보(학번, 학생이름, 주소)
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT
WITH READ ONLY;



